In [37]:
import pandas as pd
import numpy as np
import copy
import re

df = pd.read_csv("SportsTweets.csv")

In [38]:
df.drop_duplicates(inplace = True)

In [39]:
df.dropna(inplace=True)

In [40]:
df.head(25)

                                                Tweet              Sport
0   rt @thehoopcentral: behind the scenes of the b...         Basketball
1         @nkcs_ad @chiefs @nkcschools well deserved!  American football
3   rt @providecontext: bron just had his 6th game...         Basketball
4   rt @nba: a jayson tatum stocking stuffer\n#nba...         Basketball
6   rt @footyaccums: soccer am taking the piss out...             Soccer
8   rt @kareem_is_it: darvin ham is legitimately o...         Basketball
10  celtics 1h -3 jaylen brown misses 3 free throw...         Basketball
12  rt @espn: these tunnel fits are ready for nba ...         Basketball
13  rt @sergioscariolo: once upon a time, in a col...         Basketball
14  well they do make us watch the lions and cowbo...  American football
15  rt @millertimelocks: cash it!\n2u pod philadel...         Basketball
18  rt @espn: the mavs' 51 third-quarter points ar...         Basketball
19  @camumacu @nba_newyork or. maybe they don't ag...         Basketball
25  @axiome_fact @chadi_tima bravo a mr lakjaa et ...             Soccer
26  nba jam t e - tournament edition (sega game ge...         Basketball
27  a baseball bat could not have hit me harder th...           Baseball
28                    84kg6kg https://t.co/w1dnsymfmx           Baseball
31  @lassscall @danorlovsky7 @49ers @chargers @bil...  American football
35  rt @bleacherreport: jayson tatum poster on gia...         Basketball
36  aberdeen want jim goodwin flak to stop as reas...             Soccer
39  @nickadamsinusa tebow was the sorriest footbal...           Baseball
40  rt @jwepp: nba on christmas > nfl on thanksgiving  American football
44    basketball malpractice. https://t.co/nybsob9mny         Basketball
46  @majorleaguem1ke why you be rocking extra smal...           Baseball
48  rt @louisvillembb: we've got a trio of #procar...         Basketball

In [28]:
def expanded(phrase):
    # specific
    phrase = re.sub(r"won\'t", "will not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)

    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    return phrase

In [41]:
for row in df.itertuples(index=True):

    # Strip the tweet for any redundant whitespaces
    df.loc[row.Index, "Tweet"] = df.loc[row.Index, "Tweet"].strip()
    

    # Change tweets to all lower case for easier language processing
    df.loc[row.Index, "Tweet"] = df.loc[row.Index, "Tweet"].lower()

    # Removes rt keyword for retweets
    df.loc[row.Index, "Tweet"] = re.sub("rt\s", "", df.loc[row.Index, "Tweet"])

    # expands contractions
    df.loc[row.Index, "Tweet"] = expanded(df.loc[row.Index, "Tweet"])

    # Removes @'s from tweets
    df.loc[row.Index, "Tweet"] = re.sub("@[A-Za-z0-9_:]+","", df.loc[row.Index, "Tweet"])

    # Removes #'s hashtags from tweets
    df.loc[row.Index, "Tweet"] = re.sub("#[A-Za-z0-9_-]*\s*","", df.loc[row.Index, "Tweet"])

    # Removes https:// and www. links from tweets
    df.loc[row.Index, "Tweet"] = re.sub("http\S+", "", df.loc[row.Index, "Tweet"])
    df.loc[row.Index, "Tweet"] = re.sub("www.\S+", "", df.loc[row.Index, "Tweet"])

    # Removes \r\n newline characters from the tweet
    df.loc[row.Index, "Tweet"] = df.loc[row.Index, "Tweet"].replace("\r\n", " ")

    # Remove parentheses, exclamation mark, question mark
    df.loc[row.Index, "Tweet"] = re.sub('[()!?]', ' ', df.loc[row.Index, "Tweet"])

    # Remove any none alphanumeric characters one more time
    df.loc[row.Index, "Tweet"] = re.sub("[^a-z0-9]"," ", df.loc[row.Index, "Tweet"])

    # Strips the tweet again just incase of any blank characters
    df.loc[row.Index, "Tweet"] = df.loc[row.Index, "Tweet"].strip()

    if len(df.loc[row.Index, "Tweet"]) == 0:
        df.loc[row.Index, "Tweet"] = np.NA

In [42]:
df.dropna(inplace=True)
df.drop_duplicates(inplace = True)

In [43]:
df = df.loc[df['Sport'].isin(['American football','Soccer', 'Basketball', 'Baseball', "Hockey"])]

In [44]:
df.reset_index(drop=True, inplace=True)

In [45]:
df.head(25)

                                                Tweet              Sport
0        behind the scenes of the best nba commercial         Basketball
1                                       well deserved  American football
2   bron just had his 6th game in a row with 30  p...         Basketball
3   a jayson tatum stocking stuffer   live on abc ...         Basketball
4   soccer am taking the piss out of salt bae afte...             Soccer
5   darvin ham is legitimately one of the worst co...         Basketball
6   celtics 1h  3 jaylen brown misses 3 free throw...         Basketball
7       these tunnel fits are ready for nba christmas         Basketball
8   once upon a time  in a cold  beautiful city in...         Basketball
9   well they do make us watch the lions and cowbo...  American football
10  cash it  2u pod philadelphia 76ers ml   130  t...         Basketball
11  the mavs  51 third quarter points are the most...         Basketball
12  or  maybe they do not against the sixers becau...         Basketball
13  bravo a mr lakjaa et merci bcp a notre roi moh...             Soccer
14  nba jam t e   tournament edition  sega game ge...         Basketball
15  a baseball bat could not have hit me harder th...           Baseball
16                                            84kg6kg           Baseball
17                                   lmao so insecure  American football
18                jayson tatum poster on giannis  via         Basketball
19  aberdeen want jim goodwin flak to stop as reas...             Soccer
20  tebow was the sorriest football and baseball p...           Baseball
21             nba on christmas   nfl on thanksgiving  American football
22                             basketball malpractice         Basketball
23  why you be rocking extra small to baseball gam...           Baseball
24  we have got a trio of in action today   at 12p...         Basketball

In [35]:
df.to_csv("CleanedSportsTweets.csv", index=False)